### ISSUE TITLE
Unable to start/join game

### ISSUE THREAD

**Issue by cybrox** [FAForever/downlords-faf-client#819]
First of all, thanks a lot for all your work on FAF. I'm really happy, I can still play Forged Alliance just like in the good old days.

So, my issue is, whenever I try to start a game, join a game or start searching for ladder 1v1, the client will give me the following error message: `You are already in a game or haven't run the connectivity test yet`.

Now, I do realize that this message is returned by the server but using the old FAF client, I can join/start/ladder normally, so I would assume it's either an issue in the client parsing the server response, or this client using another API which, for some reason, thinks I am still ingame.

According to the logs, this happens when joining:
```
2018-03-24 12:43:21.694  INFO 13464 --- [JavaFX Application Thread] c.faforever.client.game.GameServiceImpl  : Joining game: 'Noobs <50g' (7672673)
2018-03-24 12:43:21.745  WARN 13464 --- [pool-2-thread-35] c.f.c.patch.BireusFeaturedModUpdater     : Error while testing http://content.faforever.com/bireus/faf/

java.io.FileNotFoundException: http://content.faforever.com/bireus/faf//info.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[na:1.8.0_152]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[na:1.8.0_152]
	at java.net.URL.openStream(Unknown Source) ~[na:1.8.0_152]
	at com.fasterxml.jackson.core.JsonFactory._optimizedStreamFromURL(JsonFactory.java:1547) ~[jackson-core-2.8.6.jar:2.8.6]
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:783) ~[jackson-core-2.8.6.jar:2.8.6]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2797) ~[jackson-databind-2.8.6.jar:2.8.6]
	at com.faforever.client.patch.BireusFeaturedModUpdater.canUpdate(BireusFeaturedModUpdater.java:57) ~[downlords-faf-client-0.8.0-beta.jar:0.8.0-beta]
	at com.faforever.client.patch.GameUpdaterImpl.updateFeaturedMod(GameUpdaterImpl.java:152) [downlords-faf-client-0.8.0-beta.jar:0.8.0-beta]
	at com.faforever.client.patch.GameUpdaterImpl.update(GameUpdaterImpl.java:75) [downlords-faf-client-0.8.0-beta.jar:0.8.0-beta]
	at com.faforever.client.game.GameServiceImpl.updateGameIfNecessary(GameServiceImpl.java:406) [downlords-faf-client-0.8.0-beta.jar:0.8.0-beta]
	at com.faforever.client.game.GameServiceImpl.lambda$joinGame$9(GameServiceImpl.java:234) [downlords-faf-client-0.8.0-beta.jar:0.8.0-beta]
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[na:1.8.0_152]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[na:1.8.0_152]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[na:1.8.0_152]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_152]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_152]

2018-03-24 12:43:21.749  INFO 13464 --- [pool-2-thread-36] c.f.c.p.GitFeaturedModUpdateTaskImpl     : Updating game files from https://github.com/FAForever/fa.git@refs/remotes/origin/deploy/faf
```

I can attach the full log if you want to, not sure how much information it discloses, so I'll just post a snippet for now

**Comment by grabby512** [comment]
This exact same thing is happening to me right now.  How do I go back to the old client?

**Comment by Geosearchef** [comment]
Hey guys, thx for reporting.

The exception shown in the log you posted is completely normal, that is about a new type of updater we're currently working on.
As far as I know this error is thrown if you haven't told the client where it can find the Forged Alliance Installation. There should be a notification in the top right asking you to do so.
You can also head over to the options (top left) and set the installation directory there.

Please let us know if this fixed your problem. (VERY IMPORTANT)

If not, we would need more of the log, it shouldn't disclose anything else than the paths it uses on your disk (which includes the name of your user directory), your global IP address and some information about your system. Especially passwords ARE NOT PRESENT in the log (normally).

If you still want to get the old client, while we (the java guys in faf) would be sad to loose you ;) it can be found on the download page of faforever.com.

**Comment by Geosearchef** [comment]
On https://faforever.com/client you can find the legacy client and the 0.8.0-beta of the java client, if by old client you mean the old version of this client (there may be a problem with featured mods with the new one currently, should be fixed asap), you can find it on the releases page in this git repo: https://github.com/FAForever/downlords-faf-client/releases/tag/v0.7.7.2-alpha
Just don't click the bell and update afterwards.

**Comment by cybrox** [comment]
Hi @Geosearchef ,

Thanks for the quick response. I'm certain the client is aware where it can find the Forged Alliance installation, considering it has worked before and according to the settings, the path is correct. (I set it again just to make sure but the error still occurs)

I uploaded the full version of the latest log, including at least one occurence of this error. You can find it [here](http://f.cybrox.eu/t/faf.log).

**Yep!**: I downgraded to `0.7.7.2-alpha` and can connect just fine. So it seems to be an issue with `0.8.0-beta`

**Comment by Geosearchef** [comment]
Thanks! Investigating.

```2018-03-24 18:19:26.959 DEBUG 15076 --- [JavaFX Application Thread] c.f.client.remote.JsonMessageSerializer  : Writing to server: {"uid": 7674367,"command": "game_join"}```

missing gameport, normally looks like:
```2018-03-24 18:38:17.892 DEBUG 7036 --- [lication Thread] c.f.client.remote.JsonMessageSerializer  : Writing to server: {"uid": 7674439,"gameport": 6112,"command": "game_join"}```

**Comment by Geosearchef** [comment]
Are you connected via proxy or via direct connection? What is the status in the bottom bar? Proxy connection or connect?

**Comment by Geosearchef** [comment]
Connectivity test did never finish.

**Comment by 1-alex98** [comment]
He means ConectivityCheckTask

**Comment by 1-alex98** [comment]
Totally unexplainable for me, the log. There is nothing connectivity realated in the log. Seems like the connectivity check is never done, but that can not be

**Comment by cybrox** [comment]
@axel1200 I chatted with @Geosearchef a bit about the issue, here's what I found:
- After updating, `0.8.0` chose `Proxy connection` by default
- After right clicking and retrying, it went to `Direct connection` and worked (cc @grabby512)
- When downgrading and upgrading again, I noticed Windows Firewall required confirmation again

Now here's the crux, from what I reproduce, when you upgrade, you start the installer. The installer will do its thing and ask you if you want to start the FAF client. If you choose to do so, the FAF client is started **and** the Windows Firewall popup appears. However, since the installer closes itself afterwards,  I assume the WIndows Firewall prompt does as well and might therefore not be noticed.

I couldn't really reproduce that but after confirming and manually retrying in the client, `0.8.0` seems to work for me.

**Comment by 1-alex98** [comment]
Yeah interesting we will have to see if we can reproduce by blocking the client manually in the firewall:wink: so we may detect the issue and give the user a hint

**Comment by micheljung** [comment]
Did i maybe build off develop?

**Comment by 1-alex98** [comment]
What do you mean? You mean it would be Ice?

**Comment by Geosearchef** [comment]
I want to add that he downgraded to 0.7.2 and then reinstalled 0.8.0 from the github releases, now it's working

**Comment by 1-alex98** [comment]
How about blocking it in the firewall

**Comment by 1-alex98** [comment]
Funny I can block in firewall and it still works 100 prozent fine
